all: compile 

compile: 
	g++ -std=c++11 -o json JSONlang_classes.cpp JSONlang_overloads.cpp sampleJSON.cpp

compile_gdb: 
	g++ -g -std=c++11 JSONlang_classes.cpp JSONlang_overloads.cpp sampleJSON.cpp